### ISSUE TITLE
Django Class Based View Example

### ISSUE THREAD

**Issue by techdragon** [miki725/django-url-filter#13]
Is it possible to get an example of how to use this library with a Class Based View? 
Either the built in Django ListView or the Django Vanilla Views ListView, would be enough to show how this can be used without DRF a bit easier than the current example of manually creating things does.

**Comment by miki725** [comment]
something like this should work:

```python
class MyListView(ListView):
    def get_queryset(self):
        qs = super(MyListView, self).get_queryset()
        return MyFilterSet(data=self.request.GET, queryset=qs).filter()
```

**Comment by miki725** [comment]
@techdragon does that help you? can I close the ticket?

**Comment by miki725** [comment]
I also added a snippet in usage docs http://django-url-filter.readthedocs.org/en/latest/usage.html#django-class-based-views
