### ISSUE TITLE
Pagination Capabilities/Support

### ISSUE THREAD

**Issue by techdragon** [miki725/django-url-filter#15]
It seems that most query filtering tools for django have poor support for paging/pagination.
Either inbuilt support, Django's built in pagination capabilities or via other existing pagination libraries/apps. 

Does django-url-filter support pagination in any way? 

If not, can we build it in or support the 'default' django mechanisms?
Being able to just add ```paginate_by = 10``` on my class based views, is pretty damn useful when trying to be productive.

**Comment by miki725** [comment]
Yes. It supports pagination. All this library does is filter querysets.
After they are filtered you can paginate via whatever method you like.
