### ISSUE TITLE
Using `__in` returns entire queryset

### ISSUE THREAD

**Issue by kyleobrien91** [miki725/django-url-filter#38]
Based on the documentation, it seems I should just be able to configure my viewset as follows and automatically get filtering. However, certain URL filtering seems to be ignored completed. 

```python
from django_filters.rest_framework import DjangoFilterBackend

class UsersViewSet(ModelViewSet):
    queryset = MyModel.objects.all()
    serializer_class = MyModelSerializer
    filter_backends = [DjangoFilterBackend]
    filter_fields = ['id']
```

Assuming that viewset maps to an endpoint like `/users/`, I should be able to use a query like `/users?id__in=1,2,3,4,5` and only see results where the ID is either 1, 2, 3, 4 or 5.

However, that's not the case. Using that minimal setup, I can only use a filter like `/users/?id=1`. As soon as I use `id__in=1,2,3,4,5`, I get my entire queryset back - all 20 users.

Am I missing a setup step?

**Comment by kyleobrien91** [comment]
I meant to include some information on my package versions

- Django==1.10.4
- djangorestframework==3.6.2
- django-url-filter=0.3.3

**Comment by miki725** [comment]
from the code sample above it does not look like you are using django-url-filter:

```python
from django_filters.rest_framework import DjangoFilterBackend
```

if you would like to use this package you can use:

```python
from url_filter.integrations.drf import DjangoFilterBackend
```

and yes once you use that `__in` should be one of available lookups.

closing issue for now however feel free to reopen or create issues if you will have further issues.

**Comment by kyleobrien91** [comment]
@miki725 - 100%. I was being an utter chop. It works perfectly.

**Comment by miki725** [comment]
@kyleobrien91 np. everyone does those... 😄
