### ISSUE TITLE
Support for fields = '__all__'

### ISSUE THREAD

**Issue by kyleobrien91** [miki725/django-url-filter#39]
I couldn't find an indication on Github, ReadtheDocs or in the code that suggests that there is support for this.

Basically, in the Meta class of a serializer, you can specify fields = '__all__' to indicate that the serializer should represent all fields in its return.

Similarly, I'm keen to see if we can currently use something like `filter_fields = '__all__'` in the view/viewset definition. 

The behaviour will then essentially automatically allow filtering on all model fields for that viewset.

Thoughts?

**Comment by kyleobrien91** [comment]
BTW - if this isn't currently supported, maybe we can exchange a quick few messages and I'm happy to get started on a PR

**Comment by miki725** [comment]
Currently if you simply define `fields` as `None` all fields will be used but as you pointed out that will not work in views so this seems like a reasonable feature to add, especially because DRF supports itself. Should be pretty simple change in https://github.com/miki725/django-url-filter/blob/master/url_filter/filtersets/base.py#L477. PR would be welcome if you would like to give this a try.

**Comment by just10minutes** [comment]
@kyleobrien91  did you get a chance to work on this?

Thanks

**Comment by pctSW1** [comment]
I have a fix for this, in url_filter/integrations/drf.py line 90 add the following code

` if filter_fields == '__all__':
            model = filter_class_default.filter_backend_class(queryset).get_model()
            all_fields = list(map(lambda x: x.attname,model._meta.fields))

            meta_kwargs = filter_class_meta_kwargs.copy()
            meta_kwargs.update({
                'model': model,
                'fields': all_fields,
            })
            meta = type(str('Meta'), (object,), meta_kwargs)

            return type(
                str('{}FilterSet'.format(model.__name__)),
                (filter_class_default,),
                {'Meta': meta}
            )`

**Comment by pctSW1** [comment]
@miki725 Sorry to bother you, but I had a quick question for as to when you think you'll be able to upload the new version to pip so I can upgrade my server?

Thanks,
Jon

**Comment by miki725** [comment]
fixed in https://github.com/miki725/django-url-filter/pull/75

@pctSW1 will release today
