### ISSUE TITLE
Installation does not install all files

### ISSUE THREAD

**Issue by eliyahen1** [miki725/django-url-filter#4]
pip install django-url-filter only the files in the root without the sub-directories.

This package seems great and I would like to try work with it! :-)

-thanks, Eli.

**Comment by miki725** [comment]
what specifically does not get installed? are you getting any errors?

**Comment by miki725** [comment]
I see what is going on. Ill push a fix for it shortly. Thanks

**Comment by miki725** [comment]
fixed in https://github.com/miki725/django-url-filter/commit/ca920c26d16d6b9da5be845916618e7cbad008f2 and already pushed to PyPI
