### ISSUE TITLE
Documentation examples don't include imports

### ISSUE THREAD

**Issue by jonathan-golorry** [miki725/django-url-filter#40]
Having the imports in the examples would be really useful, especially since you have two different `DjangoFilterBackend` classes (thankfully they take different numbers of `__init__` arguments, otherwise I would have been extremely confused).

**Comment by miki725** [comment]
was resolved in https://github.com/miki725/django-url-filter/commit/3647f20ae62dce4ef689763ca89162cbb7fcdbea
