### ISSUE TITLE
Use tox for testing in travis

### ISSUE THREAD

**Issue by haakenlid** [miki725/django-url-filter#51]
Currently only django 1.11 is tested in travis, because the MakeFile command doesn't run tox. Instead theres' 

It's rather confusing to have a tox config and not actually use it for continuous integration. Tox is more configurable than just using varibles in the .travis.yml file.

https://github.com/miki725/django-url-filter/blob/master/Makefile
https://github.com/miki725/django-url-filter/blob/master/.travis.yml

There is a tox config file, but there's some problems when installing pip packages with pypy. 
https://github.com/miki725/django-url-filter/blob/master/tox.ini

**Comment by miki725** [comment]
2 reasons:

* travis runs each py version under a different job which shows nicely in the UI if something broke
* tox runs a bigger matrix of dependencies and I dont want to unnecessarily burden travis

**Comment by haakenlid** [comment]
My pull request looked fine on travis, but actually broke with django 1.8. You have to remember to run tox locally to actually make sure there's no regression. That's problematic. Also, django 2.0 does not support python 2 at all, so you need to reconfigure something in any case if you want to support the current version of django.

https://travis-ci.org/miki725/django-url-filter/builds/316887097

**Comment by haakenlid** [comment]
I believe that when you use tox-travis, you get each environment as a different job. 
https://tox-travis.readthedocs.io/en/stable/
