### ISSUE TITLE
URL filter negative lookup logic is counterintuitive / faulty

### ISSUE THREAD

**Issue by webrunners** [miki725/django-url-filter#53]
With current library, it is possible to have negative lookups, like this:
`title__contains!=WIP` will yield all the entries not containing "WIP", which works well.

Now, let's suppose we want to have all entries not containing WIP which are authored by 'admin'. No problem, we just add another clause here: `title__contains!=WIP&author=admin`.

But what if we also want filter this set down by adding a condition of entry not having 'draft' status? Logic tells us to add another negative condition: `title__contains!=WIP&author=admin&status!=draft`.

Unfortunately, with current implementation, it'll result to the following SQL: `select * from entry_entries where author = 'admin' and not (title like '%WIP%' and status='draft')` which seems a bit illogical. Correct (IMO) behavior would translate this filter URL to `select * from entry_entries where author = 'admin' and not title like '%WIP%' and not status = 'draft'`.

The reason is that implementation of filtering tries to deal with multiple positive and negative filters similarly:
        include = {self._prepare_spec(i): i.value for i in self.includes}
        exclude = {self._prepare_spec(i): i.value for i in self.excludes}

        if include:
            queryset = queryset.filter(**include)
        if exclude:
            queryset = queryset.exclude(**exclude)

However, .exclude() logic with multiple kwargs differs from .filter(). Django doc suggests to use chained .exclude() instead to achieve similarity to .filter()

That's why I suggest to fix this logical issue by changing implementation.

**Comment by miki725** [comment]
@webrunners thanks. this makes sense. will include in next release.

**Comment by askoretskiy** [comment]
Could you merge this? It solves our problem with filtering.
