### ISSUE TITLE
Fix the docs in url_filter/integrations/drf_coreapi.py

### ISSUE THREAD

**Issue by user-name-is-taken** [miki725/django-url-filter#84]
Here's a [link](https://github.com/miki725/django-url-filter/blob/924c7b1e07e5855234ffcc28c11f10732fd5390e/url_filter/integrations/drf_coreapi.py) to the file. Currently the docs for `iregex` say `Case insensitive match when value is within comma separated range`, which is wrong.

**Comment by miki725** [comment]
fixed in https://github.com/miki725/django-url-filter/commit/a84399b59b73988e7fed070155ed4d4795139575. thanks for the report

**Comment by miki725** [comment]
new 0.3.13 was just release to pypi. feel free to upgrade
