### ISSUE TITLE
DateTime __date filter not working

### ISSUE THREAD

**Issue by danousna** [miki725/django-url-filter#92]
Hi there,

I am trying to filter according to the following query : `received_at__date=2020-01-5`.
The model attribute `received_at` is a DateTime field. I want to filter according to a date, not a datetime.

Using [django query filter](https://docs.djangoproject.com/fr/3.0/ref/models/querysets/#date) does return one object : 
```python
Foo.objects.filter(received_at__date="2020-01-5") 
# returns: <QuerySet [<Foo: Foo object (...)>]>
```

However, using this package does not return anything and I can't understand why :
```python
class FooFilterSet(ModelFilterSet):
    class Meta(object):
        model = Foo

query = QueryDict('received_at__date=2020-01-5')
fs = FooFilterSet(data=query, queryset=Foo.objects.all())
fs.filter() 
# returns: <QuerySet []>
```

Every other filter types work correctly.

```
Django==2.1.4
django-url-filter==0.3.14
```

Thanks for your help.

**Comment by miki725** [comment]
try adding strict mode:

```python
class MyFS(ModelFilterSet):
    default_strict_mode = StrictMode.fail
    ...
```

something tells me form field does not like `2020-01-5` and wants `2020-01-05`

**Comment by danousna** [comment]
Ok, I did try with `05` before and it also didn't work.

I set the StrictMode and I have the following error : 
```
django.core.exceptions.ValidationError: {'received_at__date': ['"date" lookup is not supported']}
```

It's a bit bizarre given that it works well when filtering via `Model.objects.filter`. I could not find anything relevant to this error anywhere.

**Comment by danousna** [comment]
Solved in #93

**Comment by danousna** [comment]
Closing this as the PR was merged.

**Comment by miki725** [comment]
sorry for the delay. this fix is now pushed to pypi

**Comment by Ilyes-git** [comment]
Hi i wanted to add an issue, 

when i try this filter on the url `opps?creation_date__date=2022-01-03 ` it works perfectly 
but when i use  `opps?creation_date__date__gt=2022-01-03 `  i have this error below
![image](https://user-images.githubusercontent.com/25868199/159126865-deedb51e-894c-487b-878a-ba36b9c3cbc1.png)
